import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { client } from "../libs/cliant";
import styles from "../styles/Home.module.css";
export const getStaticProps = async () => {
  const data = await client.get({
    endpoint: "blog",
  });
  console.log(data);
  return {
    props: {
      blog: data.contents,
    },
  };
};
export default function Home({ blog }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {blog.map((blog) => (
          <div key={blog.id}>
            <Link href={`blog/${blog.id}`}>{blog.title}</Link>
          </div>
        ))}
      </main>
    </div>
  );
}
